export enum IndustryType {
  ACCOUNTING = "accounting",
  ADVERTISING = "advertising",
  AGRICULTURE = "agriculture",
  CONSTRUCTION = "construction",
  CONSULTING = "consulting",
  DESIGN = "design",
  EDUCATION = "education",
  ENERGY = "energy",
  FINTECH = "fintech",
  GOVERNMENT = "government",
  HEALTHCARE = "healthcare",
  HOSPITALITY = "hospitality",
  HUMAN_RESOURCES_MANAGEMENT = "human_resources_management",
  IT = "it",
  LEGAL_SERVICES = "legal_services",
  MANUFACTURING = "manufacturing",
  MARKETING = "marketing",
  MEDIA_ENTERTAINMENT = "media_entertainment",
  NON_PROFIT = "non_profit",
  OTHER = "other",
  PROFESSIONAL_SERVICES = "professional_services",
  PUBLIC_RELATIONS = "public_relations",
  REAL_ESTATE = "real_estate",
  RETAIL = "retail",
  SCIENTIFIC_RESEARCH = "scientific_research",
  SOFTWARE_DEVELOPMENT = "software_development",
  TELECOMMUNICATIONS = "telecommunications",
  TOURISM = "tourism",
  TRAINING_DEVELOPMENT = "training_development",
  TRANSPORTATION = "transportation",
}

export const INSUDTRY_TYPES_IN_ORDER: IndustryType[] = [
  IndustryType.FINTECH,
  IndustryType.HEALTHCARE,
  IndustryType.EDUCATION,
  IndustryType.RETAIL,
  IndustryType.MANUFACTURING,
  IndustryType.NON_PROFIT,
  IndustryType.CONSTRUCTION,
  IndustryType.REAL_ESTATE,
  IndustryType.GOVERNMENT,
  IndustryType.TRANSPORTATION,
  IndustryType.ENERGY,
  IndustryType.AGRICULTURE,
  IndustryType.TOURISM,
  IndustryType.HOSPITALITY,
  IndustryType.MEDIA_ENTERTAINMENT,
  IndustryType.IT,
  IndustryType.TELECOMMUNICATIONS,
  IndustryType.PROFESSIONAL_SERVICES,
  IndustryType.SCIENTIFIC_RESEARCH,
  IndustryType.CONSULTING,
  IndustryType.LEGAL_SERVICES,
  IndustryType.ACCOUNTING,
  IndustryType.MARKETING,
  IndustryType.ADVERTISING,
  IndustryType.PUBLIC_RELATIONS,
  IndustryType.DESIGN,
  IndustryType.SOFTWARE_DEVELOPMENT,
  IndustryType.HUMAN_RESOURCES_MANAGEMENT,
  IndustryType.TRAINING_DEVELOPMENT,
  IndustryType.OTHER,
];
